### ISSUE TITLE
Penguin Name doesn't work

### ISSUE THREAD

**Issue by Sins1** [Times-0/Timeline#7] opened 2019-02-20 18:02 UTC
Why penguin (no moderator) are with a name: P(id) in game ? How to resolve this ? (sorry i'm french)

TEXT IN FRENCH : Pourquoi les pingouins (non modérateurs) ont un nom sous la forme P(id) dans le jeu ? Comment resoudre cela ?

**Comment by valid22** [comment] 2019-02-21 00:58
When exactly does this happen? Like after you register a new penguin?
There could be 2 reasons
1. If you were using the register, then you might want to verify your email to get the nickname as you've set
2. If above is not the case, go to avatars table and check if language set is not 0. (Language as 45 should fix it)

**Comment by Sins1** [comment] 2019-02-21 07:49
Oh thanks you ! (i can't use the register-master because when i click on the final button, i go to the URL "javascript(0);" )

**Comment by valid22** [comment] 2019-02-21 11:39
I assume this issue is being fixed then?

**Comment by valid22** [comment] 2019-02-21 11:41
In any case, I recommend using the latest login system instead (https://times-0.github.io/docs/register-login.html)

**Comment by Sins1** [comment] 2019-02-23 18:05
Hello, i download it but the sign up doesn't work (click = nothing happen) but the sign in yes and how to add the friends list on this ?

**Comment by Sins1** [comment] 2019-02-23 20:43
And the login set my database change my password when connect example password = 098f6bcd4621d373cade4e832627b4f6 (md5 = test) it become password = firebase. How to disabled this ?

**Comment by valid22** [comment] 2019-02-24 06:28
I'm quite lazy 😂😅, sign up I didn't implement yet. But you need not sign up to login using Google/Twitter/GitHub 😋

And no that is intended. The password stored is md5, and is less secure in these days, in order to overcome this, I have switched to firebase by Google for more secured login interface. You need not worry, it's just for added security

**Comment by Sins1** [comment] 2019-02-24 08:03
Ok 🤣 but i can t connect to my account in CPPS  because i think it use MD5 ( i don t use the autologin cause dont work for me)

**Comment by Sins1** [comment] 2019-02-24 08:05
So if you are some disabled to change this password (i think it s on the flex.py i have to change i try a lot but nothing work)

**Comment by valid22** [comment] 2019-02-24 08:33
It doesn't work? U sure you followed the tut, coz if it changed password as
firebase, you are almost completed. Make sure you have updated timeline to
v7.2, have the client swf dependency, and edited dependency.json, look so
there docs for more detailed intel

**Comment by Sins1** [comment] 2019-02-24 10:33
I update timeline but i can't run the server i've got a lot of :  
  INFO     | <twisted.internet.tcp.Connector instance at 0x0000000003F88348> will retry in 2 seconds
  INFO     | Stopping factory <txredisapi.RedisFactory instance at 0x0000000003F881C8>
  INFO     | Starting factory <txredisapi.RedisFactory instance at 0x0000000003F881C8>

**Comment by valid22** [comment] 2019-02-24 10:34
That explains why, you need to have redis server running

**Comment by Sins1** [comment] 2019-02-24 10:42
But the 7.1 work with no redis (only the redisapp) how to have a redis server

**Comment by valid22** [comment] 2019-02-24 10:47
7.2 will work with same as the redis you used for 7.1, make sure it's
running

**Comment by Sins1** [comment] 2019-02-24 10:50
i don't running redis in 7.1 :') i installed the txredisapp but i don't run redis ;') (i'm on windows with XAMPP and Python 2.7.X

**Comment by valid22** [comment] 2019-02-24 10:54
You need to (install redis if not before, look at first section of docs)
and run redis

**Comment by valid22** [comment] 2019-02-24 11:52
To install redis on Windows use

https://github.com/downloads/rgl/redis/redis-2.4.6-setup-64-bit.exe

https://github.com/downloads/rgl/redis/redis-2.4.6-setup-32-bit.exe

**Comment by Sins1** [comment] 2019-02-24 13:53
(IN FRENCH)
Mais je suis vraiment obligé de mettre l'"autologin.swf" ou je peux le zapper un peu ? Merci pour redis ça a l'air de remarcher à la perfection ;)

**Comment by valid22** [comment] 2019-02-24 14:02
I don't quite understand, but I'm sure you zapped it to perfection!! 😁😄

**Comment by Sins1** [comment] 2019-02-24 14:03
J'ai mis l'autologin mais ça marche toujours pas :( ça me fait une "Connection $fire" et après le jeu dit "tu n'arrives pas à te connecter...."

**Comment by Sins1** [comment] 2019-02-24 14:05
Et donc après : http://prntscr.com/mpewp2 (i use the french version ;) ) Merci pour votre investissement extraordinaire dans ce projet ;)

**Comment by valid22** [comment] 2019-02-24 14:06
😅 what? I don't understand.

**Comment by Sins1** [comment] 2019-02-24 14:07
![image](https://user-images.githubusercontent.com/47791552/53300315-cde8dd80-3845-11e9-9841-69c78aa04fc6.png)
The auto login glitch a lot :''')))

**Comment by valid22** [comment] 2019-02-24 14:08
It's not a glitch 😅, that's intended behaviour. $fire = secure as fire 🔥🔥

**Comment by Sins1** [comment] 2019-02-24 14:09
I can't connect after the password change in "firebase". And after i can't connect
![image](https://user-images.githubusercontent.com/47791552/53300353-2fa94780-3846-11e9-8bc2-ff3d8d0f44ed.png)
"This server connection doesn't work...."

**Comment by valid22** [comment] 2019-02-24 14:11
Check Timeline console. What does it say, can u pic console one u try to
login?

**Comment by Sins1** [comment] 2019-02-24 14:14
![image](https://user-images.githubusercontent.com/47791552/53300399-e4dbff80-3846-11e9-948e-e0c69cd06144.png)

**Comment by valid22** [comment] 2019-02-24 14:15
It works!? The server seems fine. BTW are you in discord?

**Comment by Sins1** [comment] 2019-02-24 14:16
No yes i've got discord but i can't use it for the moment

**Comment by Sins1** [comment] 2019-02-24 14:17
Oh and i've got this 
![image](https://user-images.githubusercontent.com/47791552/53300417-41d7b580-3847-11e9-8553-31e8c98e5f85.png)

**Comment by valid22** [comment] 2019-02-24 14:21
Check timeflex console

**Comment by Sins1** [comment] 2019-02-24 14:24
![image](https://user-images.githubusercontent.com/47791552/53300485-38028200-3848-11e9-9d3e-2c5f3c37e05a.png)

**Comment by valid22** [comment] 2019-02-24 14:27
That's fine that won't affect game login. Can you login yet?

**Comment by Sins1** [comment] 2019-02-24 14:28
No i can't :(

**Comment by Sins1** [comment] 2019-02-24 14:34
(for information, i change my name of my server did there is one thing to change ?)
![image](https://user-images.githubusercontent.com/47791552/53300579-ac89f080-3849-11e9-8ae4-3425e5edabff.png)

**Comment by Sins1** [comment] 2019-02-24 14:37
OH I FIND IN THE MEMBER.JS ! I FORGOT TO SET LOGIN NOT LOCALHOST BUT 192.168.0.2 ! Thanks for all !
![image](https://user-images.githubusercontent.com/47791552/53300625-2e7a1980-384a-11e9-9d56-48b1c97d6e82.png)
But a 2 new questions : 
How to add the "Chose your server" and the friends list ??

**Comment by valid22** [comment] 2019-02-24 14:43
For friends list follow the docs, Friend section under mediaserver topic.

`Choose your server` do u really need it? Because this is autologin, and mostly all cpps have just 1 server :male_shrug: autologin automatically chooses a server and logs you in

**Comment by Sins1** [comment] 2019-02-24 14:44
Okay so i have to change on the /member/dashboard/index.html ?

Yes i don't realy have to use a lot of servers.

**Comment by valid22** [comment] 2019-02-25 01:11
Yup

**Comment by valid22** [comment] 2019-02-27 01:38
Marking this as fixed.

**Closed as completed by valid22** 2019-02-27 01:38 UTC
Labels: fixed
